import { Navbar } from '@/components/navbar/navbar';
import { FooterSection } from '@/components/sections';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Compa Suds Detailing',
  description: 'Generated by create next app',
  icons: {
    icon: [
      { url: '/favicon.ico' },
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
    ],
    apple: [{ url: '/apple-touch-icon.png' }],
    other: [
      { url: '/android-chrome-192x192.png' },
      { url: '/android-chrome-512x512.png' },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Navbar />
        <main className='flex-1 w-full'>
          <div className='max-w-[2520px] mx-auto'>{children}</div>
        </main>
        <FooterSection />
      </body>
    </html>
  );
}
