import { Navbar } from '@/components/navbar/navbar';
import { FooterSection } from '@/components/sections';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Compa Suds Detailing',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/favicon.ico' sizes='any' />
        <link
          rel='icon'
          href='/favicon-16x16.png'
          type='image/png'
          sizes='16x16'
        />
        <link
          rel='icon'
          href='/favicon-32x32.png'
          type='image/png'
          sizes='32x32'
        />
        <link
          rel='apple-touch-icon'
          href='/apple-touch-icon.png'
          sizes='192x192'
        />
        <link
          rel='android-chrome'
          href='/android-chrome-192x192.png'
          sizes='192x192'
        />
        <link
          rel='android-chrome'
          href='/android-chrome-512x512.png'
          sizes='512x512'
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Navbar />
        <main className='flex-1 w-full'>
          <div className='max-w-[2520px] mx-auto'>{children}</div>
        </main>
        <FooterSection />
      </body>
    </html>
  );
}
